name: Deploy to server

on:
  push:
    branches: [ "main" ]
# to-do сделат универсальный pipeline:
# 1) скопировать файлы на сервер
# 2) создать службу если нет и запустить ее
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.APP_DIR }}
            git pull origin main
            sudo /usr/bin/systemctl restart income_expense_bot.service
            sudo /usr/bin/systemctl status income_expense_bot.service
          EOF